spring.application.name=backend

# Configuración segura usando variables de entorno independientes
spring.datasource.url=jdbc:postgresql://db.idnwqvhrlfnnlwaihaca.supabase.co:5432/postgres
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto dinámico requerido por Render
server.port=${PORT:8080}